# Configuration of database connection.
Database:
  driver  : com.mysql.jdbc.Driver
  url     : jdbc:mysql://localhost:3306
  username: username
  password: password

# Configuration of Discord connection
Discord:
  token: token
  prefix: >
  kingdomOwnerRoleID: 000000000000000000